-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: autopep8-wrapper
        args: [--max-line-length=100, --in-place]
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=100]
